name: Mercury wheels Build and Publish cibuildwheels

on:
  workflow_dispatch:
#  push:
#    branches:
#      - main
#      - feature/python-packages-workflow

jobs:
  build-mercury-wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          detch-depth: 1

      - name: Install packages
        run: sudo apt-get update && sudo apt-get install -y zlib1g-dev libssl-dev make

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Install pip packages
        run: python -m pip install cython cibuildwheel==2.20.0

      - name: Build Mercury
        run: ./configure && make

      - name: Build wheels
        working-directory: ./src/cython/
        run: python -m cibuildwheel --output-dir ./wheelhouse
        env:
          ENV_CFLAGS: "-DSSLNEW"
          CIBW_ARCHS_LINUX: auto x86_64 aarch64
