name: Mercury wheels Build and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/python-packages-workflow

jobs:
  build-mercury-wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          detch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install packages
        run: sudo apt-get update && apt-get-install zlib1g-dev libssl-dev make

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.20.0

      - name: Build Mercury
        run: make clean && ./configure && make && cd src/cython/

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
