name: Trigger downstream pipelines in another repos

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/python-packages-workflow

jobs:
  trigger-downstream:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger downstream
        run: |
          # Set the required variables
          repo_owner="REPOSITORY OWNER" 
          repo_name="REPOSITORY NAME"  
  
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.WORKFLOW_PAT_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/SvyatoslavFedynyak/mercury-python/actions/workflows/build-wheels/dispatches